[package]
name = "cli-tool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"]}
indicatif = {version = "0.17.8"}
log = {version = "0.4"}
env_logger = "0.10"